services:
  bot:
    build: ./
    restart: always
    command: node bot.js
    volumes:
      - .:/bot
  command:
    build: ./
    command: node command.js
  voice:
    image: voicevox/voicevox_engine:cpu-latest
    platform: linux/amd64
    ports:
      - 50021:50021
    restart: always
